default_language_version:
  python: python3.12
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/ambv/black
  rev: 23.7.0
  hooks:
  - id: black

- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black]

- repo: https://github.com/PyCQA/flake8.git
  rev: 6.1.0
  hooks:
  - id: flake8
    # additional_dependencies:
    # - flake8-print==5.0.0
    exclude: notebooks
    args: [ '--config=./.flake8']

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort

# - repo: https://github.com/econchick/interrogate
#   rev: 1.5.0
#   hooks:
#   - id: interrogate
#     pass_filenames: false
#     args: [--config=pyproject.toml]
#     language_version: python3.12
